---
title: "Experiment 2 data analysis"
output: html_notebook
---

```{r}
rm(list = ls())
library(langcog)
library(tidyr)
library(dplyr)
library(ggthemes)
theme_set(theme_minimal(9))

```

Data analysis for Class Elicitation experiment

```{r}
data.path <- "../data/"
```

```{r}
project.name <- "vague-prior-elicitation-1"

d.subject <- read.csv(paste("../data/", 
                            project.name, 
                            "-subject_information.csv", sep = ""))
table(d.subject$enjoyment)
```

Note: `d.catch` and `d` only include 264 rows because I accidentally collected 36 subjects on the slider task. 
The slider subjects are already removed.

```{r}
d.catch <- read.csv(paste(data.path, 
                          project.name, 
                          "-catch_trials.csv", sep = ""))
d.catch <- d.catch %>% 
  mutate(pass = response == "Yes")

sum(d.catch$pass)
```


```{r}
d <- read.csv(paste("../data/", project.name, "-trials.csv", sep = ""))
```

```{r}
table(d$sub_category, d$form, d$condition) %>% data.frame() %>% 
  ggplot(.,aes(x = Freq))+
  geom_histogram()+
  xlab("Number of subjects/responses per unique item")
```

Bootstrap confidence intervals (uses `langcog` package)
```{r}
df.summary <- d %>%
  group_by(strength, target, degree, adjective, form, sub_category, super_category) %>%
  multi_boot_standard(column = "response")
```


```{r}
df.summary %>%
  ungroup() %>%
  mutate(experiment = 'Adjective endorsement \n data',
          sub_category = factor(sub_category, 
                  levels = c("gymnast", "soccer player", "basketball player",
                             "bottle opener", "toaster", "dishwasher",
                             "day in Winter", "day in Fall", "day in Summer",
                             "video of the cute animal", "music video", "movie",
                             "grape", "apple", "watermelon"),
                  labels = c("gymnast", "soccer player", "basketball player",
                             "bottle opener", "toaster", "dishwasher",
                             "day in Winter", "day in Fall", "day in Summer",
                             "cute animal video", "music video", "movie",
                             "grape", "apple", "watermelon") )) %>%
  ggplot(., 
         aes( x = sub_category, y = mean, ymin = ci_lower, ymax = ci_upper, group = form, fill = form ) )+
  geom_bar(stat = 'identity', position = position_dodge(), alpha = 1, 
           color = 'black', width = 0.9) +
  geom_errorbar(position = position_dodge(0.9), width = 0.3) +
  facet_grid(experiment~degree, scales = 'free') +
  ylim(0, 1) +
  scale_fill_brewer(palette = 'Set3') +
  ylab("Superordinate paraphrase   ") +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.95),
        axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.line = element_line(colour = "black"))

ggsave("~/Documents/research/comparison-class/posters/fig/expt2_data.pdf", height = 2.5)
```

